# Generated by Django 4.1.6 on 2024-06-18 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_description_alter_todo_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-id"]},
        ),
    ]
